ALTER TABLE notifications DROP CONSTRAINT IF EXISTS notifications_type_check;
ALTER TABLE notifications ADD CONSTRAINT notifications_type_check 
CHECK (type IN ('NEW_OFFER', 'OFFER_ACCEPTED', 'OFFER_REJECTED', 'ORDER_CREATED', 
'ORDER_SHIPPED', 'ORDER_DELIVERED', 'ORDER_CANCELLED', 'PRODUCT_APPROVED', 
'PRODUCT_REJECTED', 'COMMENT_RECEIVED', 'COMMENT_REPLIED', 'PAYMENT_RECEIVED', 
'PAYMENT_REFUNDED', 'SELLER_VERIFIED', 'ACCOUNT_VERIFIED', 'SYSTEM_MESSAGE', 
'NEW_MESSAGE', 'PRICE_UPDATE', 'STOCK_UPDATE', 'FOLLOW_REQUEST', 
'ORDER_STATUS_CHANGE', 'OFFER_STATUS_CHANGE', 'PRODUCT_STATUS_CHANGE', 
'PRODUCT_REVIEW', 'PRODUCT_COMMENT', 'PRODUCT_QUESTION', 'PRODUCT_ANSWER')); 